import { Knex } from 'knex'
import fs from 'fs'
import path from 'path'

const getRecipe = (fileName: string): string => {
  const file = path.join(__dirname, 'recipes', fileName)
  return JSON.stringify(fs.readFileSync(file, 'utf8'))
}

export async function seed(knex: Knex): Promise<void> {
  await knex.raw(
    'TRUNCATE TABLE users, cookbook_members, cookbooks, recipes, ingredients, ingredient_types, tags, tag_types RESTART IDENTITY;'
  )

  await knex('users').insert([
    {
      guid: 'auth0|64372a666cf43922a23a8e31',
      username: 'clinzy',
      email: 'email@email.com',
      password: 'asdfabisdfybiasfgd',
      is_readonly: 0,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      guid: 'auth0|64372a666cf43922a23a8e32',
      username: 'qnt3n',
      email: 'email@email.com',
      password: 'asdfabisdfybiasfgd',
      is_readonly: 0,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      guid: 'auth0|64372a666cf43922a23a8e33',
      username: 'curbins',
      email: 'email@email.com',
      password: 'asdfabisdfybiasfgd',
      is_readonly: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ])
  await knex('cookbooks').insert([
    {
      creator_user_id: 1,
      cookbook_name: 'Conner shared cookbook',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      creator_user_id: 2,
      cookbook_name: 'Quinten family cookbook',
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ])
  await knex('cookbook_members').insert([
    {
      creator_user_id: 1,
      member_user_id: 2,
      cookbook_id: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
      invitation_accepted: 1,
    },
    {
      creator_user_id: 1,
      member_user_id: 3,
      cookbook_id: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ])
  await knex('recipes').insert([
    {
      cookbook_id: 1,
      creator_user_id: 1,
      name: 'Homemade Spinach Pasta',
      image: 'https://howtofeedaloon.com/wp-content/uploads/2023/04/spinach-linguine-IG.jpg',
      description:
        'Homemade spinach pasta takes many pasta dishes to levels you just can&#39;t believe. Don&#39;t let the dough become too dry, but also incrementally add more flour if too wet. See the video (in the blog post) for visual guidance.',
      cook_time: '3 minutes',
      cook_original_format: 'PT3M',
      prep_time: '60 minutes',
      prep_original_format: 'PT60M',
      total_time: '63 minutes',
      total_original_format: 'PT63M',
      yield: '8',
      ingredients: JSON.stringify([
        '8 oz spinach (fresh, washed and stems removed)',
        '2 large eggs (room temperature)',
        '1 tbsp olive oil',
        '1/2 tsp salt',
        '3/4 cup semolina flour',
        '1 cup all-purpose flour (plus more for handling pasta)',
      ]),
      instructions: JSON.stringify([
        'Bring a pot of salted water to a boil.',
        'Cook spinach for about 2 to 3 minutes, until fully wilted.',
        'Drain spinach, when cool enough to handle, press out excess water. Roughly chop with a large knife. Set aside.',
        'In a small bowl, add the eggs, olive oil, and salt. Mix together with a fork.',
        'Add egg mixture to a food processor and pulse a few times. Add the cooked spinach and pulse several times until combined with the egg mixture.',
        'With the motor running, slowly add the semolina flour through the tube. Next, add the all-purpose flour. Keep processing, pulsing if desired, until a ball forms. You may need to add more flour if the dough is too wet to form a ball.',
        'Dust hands with flour, and remove the dough from the food processor. Dust the dough with plenty of flour, and form into a ball.',
        'Divide into 4ths, and cover each with plastic wrap, place in the refrigerator, and let rest for 10 minutes.',
        'Take the first 4th of the dough, and flatten with your hand into a round disc, dusting with flour if too wet to the touch.',
        'Use a rolling pin to flatten the dough into a rectangle.',
        'Fold the right side in, and then the left, and roll again to flatten. Repeat this 5 times.',
        'Attach the pasta roller to your stand mixer, and place it on the widest setting. If using a manual pasta roller, set it to the widest setting.',
        'Carefully lower the dough through the roller.',
        'Continue to fold the edges in, like an envelope, for another 5 times, keeping the roller on the widest setting.',
        'The dough is now ready for turning into pasta. Move to the next setting (usually the #2 setting) and place the dough through the roller. Move to the next setting (usually the #3 setting). Continue this process until you&#39;ve reached the desired thickness of the pasta. You may need to cut the pasta sheet in half during this process. If desired, change to the linguine or angel hair attachment, and then cut the pasta.',
        'Once ready, place on a baking sheet lined with parchment (or wax) paper that has been sprinkled with semolina (or cornmeal) (this keeps the pasta from sticking to each other). Sprinkle with more semolina. Cover the pasta with a kitchen towel.',
        'Repeat the process with each other quarters of the pasta. As one layer is filled on the baking sheet, place parchment or wax paper on the pasta, sprinkle with more semolina, and continue.',
        'Once the pasta has been rolled out, bring a large pot of salted water to a boil.',
        'Drop the pasta into the boiling water and cook for 3 minutes, or until fully cooked (don&#39;t overcook it!).',
        'Drain. The pasta is now ready to use in your favorite pasta recipes!',
      ]),
      source_url: 'https://howtofeedaloon.com/fresh-spinach-pasta/',
      source_type: 'link',
      is_private: 0,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      cookbook_id: 1,
      creator_user_id: 1,
      name: 'Korean Ground Beef Bowls (Easy 30 Minute Meal)',
      image:
        'https://therealfooddietitians.com/wp-content/uploads/2022/05/Korean-Beef-Bowls-2-225x225.jpg',
      description:
        'These Korean-inspired beef bowls are packed with flavor, protein, and color and ready in under 30 minutes.',
      cook_time: '10 minutes',
      cook_original_format: 'PT10M',
      prep_time: '15 minutes',
      prep_original_format: 'PT15M',
      total_time: '25 minutes',
      total_original_format: 'PT25M',
      yield: '4',
      ingredients: JSON.stringify([
        '1 lb. (16 ounces) Silver Fern Farms Net Carbon Zero By Nature 100% Grass-Fed Angus Ground Beef',
        '⅓ cup coconut aminos*',
        '1 tablespoon toasted sesame oil',
        '2 teaspoons honey',
        '2 tablespoons rice vinegar',
        '3 garlic cloves, minced',
        '1/4 &#8211; 1/2 teaspoon crushed red pepper flakes (adjust to taste)',
        '1/4 teaspoon ground ginger (may substitute 1 teaspoon grated fresh ginger)',
        '3 green onions, sliced, green and light green/white parts separated',
        '3 cups cooked white rice or brown rice',
        '1 teaspoon sesame seeds',
        '1 large cucumber, thinly sliced or cut into strips using a vegetable peeler',
        '8 radishes, trimmed and thinly sliced',
        '2 medium carrots, shredded or julienned',
        'Optional: Sriracha or chili-garlic sauce, to taste',
      ]),
      instructions: JSON.stringify([
        'Place a medium or large skillet over medium-high heat on the stovetop. When the skillet is hot, add the ground beef to the skillet, stirring and crumbling into small pieces with a wooden spoon, until cooked through. Drain off any excess liquid then return the skillet to the stove.',
        'While the beef is cooking, in a small bowl, whisk together the coconut aminos, honey, sesame oil, rice vinegar, garlic, red pepper flakes, and ginger.',
        'Add the sauce and the light green and white parts of the green onions to the ground beef. Stir and cook for 1-2 minutes to bring the sauce to a simmer and allow some of the sauce to absorb into the meat (but not so long as to evaporate).',
        'Remove from heat and serve the ground beef mixture over hot cooked rice with cucumber, radish, and carrot. Garnish with green onion and sesame seeds. Serve with sriracha or chili-garlic sauce, if desired.',
      ]),
      source_url: 'https://therealfooddietitians.com/korean-inspired-ground-beef-bowls/',
      source_type: 'link',
      is_private: 0,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      cookbook_id: 1,
      creator_user_id: 1,
      name: '30-Minute Tofu Pad Thai',
      image:
        'https://www.simplyquinoa.com/wp-content/uploads/2022/01/30-minute-tofu-pad-thai-2.jpg',
      description:
        'This super easy tofu pad thai recipe takes 30 minutes, is healthy, gluten-free and vegetarian. It tastes like takeout, but without any junk! Made with egg, peanut butter and coconut sugar!',
      cook_time: '25 minutes',
      cook_original_format: 'PT25M',
      prep_time: '5 minutes',
      prep_original_format: 'PT5M',
      total_time: '30 minutes',
      total_original_format: 'PT30M',
      yield: '4',
      ingredients: JSON.stringify([
        '14 oz rice noodles ((preferably stir fry/pad thai style))',
        '14 oz extra firm tofu',
        '1 tablespoon olive oil',
        '1 cup bean sprouts',
        '1 cup shredded carrots',
        '2 cloves garlic (, grated or minced)',
        '2 eggs',
        '1 cup green onions',
        '1/2 cup cilantro',
        '1/2 - 1 whole lime',
        '1/2 - 1 tsp pepper flakes',
        '1/4 cup chopped peanuts',
        '3 tablespoons soy sauce',
        '2 tablespoons fish sauce',
        '1/4 cup coconut sugar',
        '1 tablespoon rice vinegar',
        '1 tablespoon peanut butter',
        'Sliced hot pepper ((optional))',
      ]),
      instructions: JSON.stringify([
        'Begin by cooking the noodles according to the package instructions. Drain once cooked.',
        'While the noodles are cooking, cut the tofu into cubes. Heat the oil in a large pan and place the tofu in the pan. Sear for 2 - 3 minutes per side. Once the tofu is seared, transfer it to a plate.',
        'Into the same skillet, add the bean sprouts, carrots, and garlic. Cook until the carrots have softened, about 3 minutes.',
        'While those are cooking, quickly whisk together the sauce.',
        'Once the veggies are done, push them to the side of the pan. Crack both eggs in the pan and scramble them. Combine with the veggies.',
        'Add the tofu, drained noodles, green onions, cilantro, lime, pepper flakes, and sauce. Toss to combine.',
        'Plate the pad thai and top with additional cilantro, chopped peanuts, sliced hot peppers, and a spritz of lime (if desired). Enjoy!',
      ]),
      source_url: 'https://www.simplyquinoa.com/30-minute-tofu-pad-thai/',
      source_type: 'link',
      is_private: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      cookbook_id: 1,
      creator_user_id: 2,
      name: 'Authentic Jambalaya',
      image: 'https://howtofeedaloon.com/wp-content/uploads/2022/02/jambalaya-IG.jpg',
      description:
        'Well, it doesn&#039;t get much better than this amazing jambalaya recipe! Classic Louisiana flavor. We love using chicken, andouille sausage and shrimp. Along with the other spices and aromatics that make this an-all favorite dish. So good!',
      cook_time: '60 minutes',
      cook_original_format: 'PT60M',
      prep_time: '20 minutes',
      prep_original_format: 'PT20M',
      total_time: '95 minutes',
      total_original_format: 'PT95M',
      yield: '8',
      ingredients: JSON.stringify([
        '3 tbsp olive oil',
        '1 lb chicken thighs (boneless, skinless)',
        'Salt and pepper',
        '1 lb andouille sausage (fully cooked and sliced into rounds (SEE NOTES))',
        '1 yellow onion (chopped)',
        '1 large green bell pepper (cored, seeded and chopped)',
        '3 celery ribs (chopped)',
        '1 jalapeno (cored, seeded, and chopped)',
        '4 garlic cloves (minced)',
        '1 tbsp tomato paste',
        '1 tbsp red wine vinegar',
        '1 tbsp hot sauce (i.e., Louisiana, Tobacco, Crystals)',
        '2 tsp fresh thyme (chopped (or 1 teaspoon, dried))',
        '1 tsp cayenne pepper',
        '1 tsp garlic powder',
        '1 tsp smoked paprika',
        '1 tsp chili powder',
        '1 28 oz. can whole tomatoes (crushed with your hands, liquid reserved)',
        '4 cups chicken stock',
        '2 bay leaves',
        '11/2 cups long-grain rice (we use white)',
        '1 lb shrimp (peeled and deveined)',
        '2 tbsp parsley (fresh, chopped, for garnish (optional))',
      ]),
      instructions: JSON.stringify([
        'Preheat oven to 350 degrees°F.',
        'Season chicken with salt and pepper.',
        'In a large heavy pot, preferably a Dutch oven, heat 1 tablespoon oil over medium-high heat.',
        'Add the chicken pieces and sauté until browned, about 5 minutes. Remove from pot and cut into bite-size pieces. Set aside.',
        'Heat the remaining 2 tablespoons of oil in the pan over medium-high heat.',
        'Add the cooked sausage and cook until starting to brown, about 4 minutes.',
        'Add all remaining ingredients, except for the shrimp and cooked chicken. Add 2 tsp of salt and 1 tsp black pepper. Stir to fully combine.',
        'Cover and cook in the oven until the rice is nice and tender, about 1 hour.',
        'Remove from oven and stir in the shrimp and cooked chicken. Return to the oven (covered) for 15 minutes. The shrimp should be nice and pink, if it doesn&#39;t look fully cooked, return to the oven for another 10 to 15 minutes.',
        'Stir with a wooden spoon and garnish with fresh parsley, if desired. Serve at once with additional hot sauce.',
      ]),
      source_url: 'https://howtofeedaloon.com/authentic-jambalaya-shrimp-chicken-smoked-ham/',
      source_type: 'link',
      is_private: 0,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      cookbook_id: 1,
      creator_user_id: 2,
      name: 'Pad Woon Sen Recipe (With Chicken)',
      image: 'https://izzycooking.com/wp-content/uploads/2020/11/Pad-Woon-Sen-thumbnail.jpg',
      description:
        'This amazing Pad Woon Sen recipe is surprisingly easy to make at home in under 30 minutes. It’s a Thai stir-fried noodle dish made with glass noodles, proteins, veggies tossed in a savory and slightly sweet pad woon sen sauce. It tastes like it came from your favorite Thai restaurant.',
      cook_time: '15 minutes',
      cook_original_format: 'PT15M',
      prep_time: '15 minutes',
      prep_original_format: 'PT15M',
      total_time: '30 minutes',
      total_original_format: 'PT30M',
      yield: '4',
      ingredients: JSON.stringify([
        '6 oz glass noodles ((dried))',
        '2 tablespoons vegetable oil (divided)',
        '1 pound chicken breasts',
        '2 tablespoons minced garlic',
        '1/2 onion ((medium-size, thinly sliced))',
        '1/2 cup thinly sliced carrots',
        '2 cups cabbage (thinly sliced (you can also sub other vegetables))',
        '1 medium tomato ((seeds removed, and sliced into thin strips))',
        '1/2 teaspoon ground white pepper ((or black pepper))',
        '2 eggs (whisked)',
        '2 green onions (chopped)',
        '2 tablespoons low-sodium soy sauce',
        '3 tablespoons oyster sauce',
        '1 tablespoon fish sauce',
        '2 tablespoons sugar',
        '1/4 cup water',
      ]),
      instructions: JSON.stringify([
        'Prepare the glass noodles: Soak the noodles in room temperature water according to package instructions. Then drain the noodles using a colander. Cut them into shorter pieces and toss with oil to prevent them from sticking.',
        'Make the sauce: While the noodles are soaking, mix together all the sauce ingredients. Set aside.',
        'Stir fry the chicken: Heat 1 tablespoon oil in a non-stick skillet or wok over medium-high heat. Add chicken pieces and sauté until cooked through, about 6 minutes.',
        'Stir fry the veggies: Transfer the chicken to a plate, and add the remaining oil to the skillet. Add garlic, and sauté for about 1 minute until fragrant. Add onions, cabbage, tomato, carrots, and white pepper to the skillet and stir-fry for about 2-3 minutes.',
        'Cook the eggs: Move the vegetables to one side of the pan, and add the beaten eggs to the empty space in the pan. Scramble the eggs until the eggs are cooked through.',
        'Stir fry everything together: Add chicken back to the skillet, and then add noodles, and the sauce. Stir-fry until the noodles are soft and everything’s coated with the sauce. (Taste and add more soy sauce if necessary. Sprinkle the chopped green onions and mix gently. If your noodles are a little dry, you can also add some water, one tablespoon at a time. )',
      ]),
      source_url: 'https://izzycooking.com/pad-woon-sen/',
      source_type: 'link',
      is_private: 0,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      cookbook_id: 1,
      creator_user_id: 2,
      name: 'Pan-Seared Halibut with Vegetables',
      image: 'https://howtofeedaloon.com/wp-content/uploads/2023/02/filet-of-halibut-IG.jpg',
      description:
        'Seared halibut is not a fishy-tasting seafood dish at all. See the NOTES for halibut substitutions. Because the dish comes together quickly, be sure to have all of your ingredients prepped and ready to go before starting.',
      cook_time: '15 minutes',
      cook_original_format: 'PT15M',
      prep_time: '15 minutes',
      prep_original_format: 'PT15M',
      total_time: '30 minutes',
      total_original_format: 'PT30M',
      yield: '4',
      ingredients: JSON.stringify([
        '4 6 oz halibut fillets',
        'Salt and freshly ground black pepper',
        '2 tbsp olive oil',
        'unsalted butter',
        '1/2 cup red onion (chopped)',
        '4 cloves garlic (minced)',
        '1 tsp rosemary (fresh, chopped (or 1/2 tsp dried))',
        '1 tsp thyme (fresh, chopped (or 1/2 tsp dried))',
        '3/4 cup cherry tomatoes (halved)',
        '2/3 cup chicken broth',
        '1/2 cup cannellini beans (drained and rinsed)',
        '5 oz spinach (fresh, stemmed, and washed)',
        '2 tbsp lemon juice (from 2 lemons)',
        '1/2 cup green olives (pitted, halved)',
        'Pinch red pepper flakes',
      ]),
      instructions: JSON.stringify([
        'Season the halibut fillets with salt and pepper.',
        'In a large skillet with a lid (non-stick is preferable), heat 2 tablespoons of the oil over medium-high heat. Once shimmering, add the butter and swirl until melted.',
        'Add the halibut and sear until golden brown on one side, about 3 minutes (you may need to do this in batches). Transfer to a plate.',
        'Add the onion and cook until soft, about 4 minutes. Add the garlic and cook, stirring often, for another 30 seconds.',
        'Stir in the rosemary, thyme, and tomatoes and cook for another 1 to 2 minutes, stirring occasionally.',
        'Add the broth and beans and bring to a simmer.',
        'Working in batches, add the spinach to the skillet and cook until completely wited down. Repeat with remaining spinach.',
        'Stir in the lemon juice, olives, red pepper flakes, ½ tsp salt, and ¼ tsp pepper. Stir to combine.',
        'Turn down the heat to medium-low and nestle the fillets into the vegetables and sauce. Cover and cook for about 3 minutes, or until fillets are completely cooked through (internal temperature of 130 to 135°F).',
        'Ladle the vegetable and bean sauce into shallow bowls and then nestle a fillet in each. Drizzle more sauce over the top. Serve at once.',
      ]),
      source_url: 'https://howtofeedaloon.com/halibut-braised-kale-beans-tomatoes/',
      source_type: 'link',
      is_private: 1,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
    {
      cookbook_id: 1,
      creator_user_id: 1,
      name: 'Crispy Garlic Butter Chicken and Brussels',
      image:
        'https://www.theendlessmeal.com/wp-content/uploads/2018/09/Garlic-Butter-Chicken-Brussels-5.jpg',
      description:
        "Garlic Butter Chicken and Brussels Sprouts is a super easy to make (5 ingredient!) and healthy autumn dinner recipe. It's made on the stovetop with only one pan so clean up is a breeze, too!",
      cook_time: '35 minutes',
      cook_original_format: 'PT35M',
      prep_time: '5 minutes',
      prep_original_format: 'PT5M',
      total_time: '40 minutes',
      total_original_format: 'PT40M',
      yield: '4',
      ingredients: JSON.stringify([
        '8 chicken thighs - skin on or off (your choice!)',
        '1 lb brussels sprouts (cut in half)',
        '1/2 teaspoon sea salt',
        '1/4 teaspoon black pepper',
        '3/4 cup chicken stock',
        '2 teaspoons butter',
        '3 cloves garlic (grated on a Microplane or very finely minced)',
      ]),
      instructions: JSON.stringify([
        'Add the chicken to a non-stick frying pan over medium-high heat skin side up. (If using skinless thighs, add a teaspoon of oil.) Sprinkle half the salt and pepper over the chicken and let it cook for 5 minutes, or until it has browned on the bottom. Flip the chicken over and sprinkle on the remaining salt and pepper. Cook until the skin is crispy or the top is brown, about 6-7 minutes. Remove the chicken from the pan.',
        'While the chicken is cooking, cut the brussels in half. Add the brussels sprouts to the pan and let them cook until they are brown on one side, about 5 minutes. Push them to the side of the pan and arrange the chicken on the other side of the pan. Pour the chicken stock into the pan (not over the crispy chicken) and let it simmer until the pan is dry and the chicken is fully cooked, about 15 minutes.',
        'Pile the brussels sprouts on one side of the pan and add the butter and garlic. Let the garlic cook for 2 minutes then spoon some garlic butter over the tops of the chicken. Mix the rest of the garlic butter into the brussels sprouts.',
        'Serve with lots of extra black pepper.',
      ]),
      source_url:
        'https://www.theendlessmeal.com/crispy-garlic-butter-chicken-and-brussels-sprouts/',
      source_type: 'link',
      is_private: 0,
      created_at: knex.fn.now(),
      updated_at: knex.fn.now(),
    },
  ])
  await knex('ingredient_types').insert([
    { ingredient_name: 'rice noodles' },
    { ingredient_name: 'bean sprouts' },
    { ingredient_name: 'soy sauce' },
    { ingredient_name: 'shredded carrots' },
    { ingredient_name: 'eggs' },
    { ingredient_name: 'meatballs' },
    { ingredient_name: 'pasta dried, such as dilatini or small elbow' },
    { ingredient_name: 'sea salt and black pepper' },
    { ingredient_name: 'ground beef' },
    { ingredient_name: 'ginger' },
    { ingredient_name: 'gochujang' },
  ])
  await knex('ingredients').insert([
    {
      ingredient_type_id: 1,
      recipe_id: 2,
      amount: 14,
      unit: 'oz',
    },
    {
      ingredient_type_id: 2,
      recipe_id: 1,
      amount: 1,
      unit: 'cup',
    },
    {
      ingredient_type_id: 3,
      recipe_id: 2,
      amount: 2,
      unit: 'tbsp',
    },
    {
      ingredient_type_id: 4,
      recipe_id: 2,
      amount: 1,
      unit: 'cup',
    },
    {
      ingredient_type_id: 4,
      recipe_id: 1,
      amount: 0.5,
      unit: 'cup',
    },
    {
      ingredient_type_id: 6,
      recipe_id: 3,
      amount: 1,
      unit: 'tray',
    },
    {
      ingredient_type_id: 7,
      recipe_id: 3,
      amount: 1,
      unit: 'lb',
    },
    {
      ingredient_type_id: 8,
      recipe_id: 1,
      amount: 2,
      unit: 'tbsp',
    },
    {
      ingredient_type_id: 9,
      recipe_id: 1,
      amount: 1,
      unit: 'tsp',
    },
  ])
  await knex('tag_types').insert([
    {
      tag_name: 'asian',
    },
    {
      tag_name: 'italian',
    },
    {
      tag_name: 'jamacian',
    },
    {
      tag_name: 'vegitarian',
    },
    {
      tag_name: 'chicken',
    },
  ])
  await knex('tags').insert([
    {
      recipe_id: 1,
      tag_type_id: 1,
    },
    {
      recipe_id: 2,
      tag_type_id: 1,
    },
    {
      recipe_id: 2,
      tag_type_id: 5,
    },
    {
      recipe_id: 3,
      tag_type_id: 2,
    },
    {
      recipe_id: 4,
      tag_type_id: 3,
    },
    {
      recipe_id: 5,
      tag_type_id: 5,
    },
  ])
}
